// SPDX-FileCopyrightText: 2026 ddosintruders
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Wallpaper-derived color scheme, generated by the Wallpapers service
// (via matugen) into ~/.config/goldensh3ll/colors.json. Theme consumes
// these tones when Settings.data.dynamicColor is enabled.

pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
    id: root

    readonly property bool available: adapter.dPrimary.length > 0

    // Dark scheme tones (with brand fallbacks so bindings stay valid).
    readonly property color dPrimary: adapter.dPrimary || "#d9a94c"
    readonly property color dOnPrimary: adapter.dOnPrimary || "#181307"
    readonly property color dSurface: adapter.dSurface || "#141519"
    readonly property color dSurfaceContainer: adapter.dSurfaceContainer || "#242830"
    readonly property color dSurfaceContainerHigh: adapter.dSurfaceContainerHigh || "#2d323c"
    readonly property color dSurfaceContainerHighest: adapter.dSurfaceContainerHighest || "#363c48"
    readonly property color dOnSurface: adapter.dOnSurface || "#f2f3f6"
    readonly property color dOnSurfaceVariant: adapter.dOnSurfaceVariant || "#b7bdc8"
    readonly property color dOutline: adapter.dOutline || "#7f8794"

    // Light scheme tones.
    readonly property color lPrimary: adapter.lPrimary || "#d9a94c"
    readonly property color lOnPrimary: adapter.lOnPrimary || "#ffffff"
    readonly property color lSurface: adapter.lSurface || "#eef0f3"
    readonly property color lSurfaceContainer: adapter.lSurfaceContainer || "#ffffff"
    readonly property color lSurfaceContainerHigh: adapter.lSurfaceContainerHigh || "#e7eaee"
    readonly property color lSurfaceContainerHighest: adapter.lSurfaceContainerHighest || "#dbdfe6"
    readonly property color lOnSurface: adapter.lOnSurface || "#1a1c20"
    readonly property color lOnSurfaceVariant: adapter.lOnSurfaceVariant || "#4d545e"
    readonly property color lOutline: adapter.lOutline || "#7b828c"

    FileView {
        path: Settings.configDir + "/colors.json"
        watchChanges: true
        onFileChanged: reload()
        printErrors: false

        JsonAdapter {
            id: adapter

            property string dPrimary: ""
            property string dOnPrimary: ""
            property string dSurface: ""
            property string dSurfaceContainer: ""
            property string dSurfaceContainerHigh: ""
            property string dSurfaceContainerHighest: ""
            property string dOnSurface: ""
            property string dOnSurfaceVariant: ""
            property string dOutline: ""

            property string lPrimary: ""
            property string lOnPrimary: ""
            property string lSurface: ""
            property string lSurfaceContainer: ""
            property string lSurfaceContainerHigh: ""
            property string lSurfaceContainerHighest: ""
            property string lOnSurface: ""
            property string lOnSurfaceVariant: ""
            property string lOutline: ""
        }
    }
}
